'use server';

/**
 * @fileOverview A product description AI agent.
 *
 * - generateProductDescription - A function that generates an improved product description using AI.
 * - GenerateProductDescriptionInput - The input type for the generateProductDescription function.
 * - GenerateProductDescriptionOutput - The return type for the generateProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  currentDescription: z.string().describe('The current description of the product.'),
  category: z.string().describe('The category of the product (e.g., food, toys, litter).'),
  keywords: z.string().describe('A comma separated list of keywords that should be included in the description.'),
});
export type GenerateProductDescriptionInput = z.infer<typeof GenerateProductDescriptionInputSchema>;

const GenerateProductDescriptionOutputSchema = z.object({
  improvedDescription: z.string().describe('An improved product description generated by AI.'),
});
export type GenerateProductDescriptionOutput = z.infer<typeof GenerateProductDescriptionOutputSchema>;

export async function generateProductDescription(input: GenerateProductDescriptionInput): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProductDescriptionPrompt',
  input: {schema: GenerateProductDescriptionInputSchema},
  output: {schema: GenerateProductDescriptionOutputSchema},
  prompt: `You are an expert eCommerce product description writer, skilled in writing compelling and SEO-friendly descriptions.

  Based on the following product information, write an improved product description.

  Product Name: {{{productName}}}
  Current Description: {{{currentDescription}}}
  Category: {{{category}}}
  Keywords: {{{keywords}}}

  The improved description should be engaging, informative, and optimized for search engines. It should be no more than 200 words.
  `,
});

const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
